---
kind: pipeline
name: docker

platform:
  os: linux
  arch: amd64

steps:
- name: porter-dry-run
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "latest"
    dry_run: true
  when:
    event:
    - pull_request

- name: porter-latest
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/drone-fossa
    tags: latest
  when:
    event:
      - push

- name: porter-release
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "${DRONE_TAG}"
  when:
    event:
    - tag

