---
kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: docker-publish-porter
  image: plugins/docker
  settings:
    context: .
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "latest"
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: docker-publish-porter
  image: plugins/docker
  settings:
    context: .
    custom_dns: 1.1.1.1
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "${DRONE_TAG}"
    username:
      from_secret: docker_username
  when:
    event:
    - tag

