---
kind: pipeline
name: docker

platform:
  os: linux
  arch: amd64

steps:
- name: porter-dry-run
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "latest"
    dry_run: true
  when:
    event:
    - pull_request

- name: porter-latest
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tags: latest
  when:
    event:
      - push

- name: porter-release
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: rancher/git-porter
    tag: "${DRONE_TAG}"
  when:
    event:
    - tag

---
kind: pipeline
name: helm

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: alpine:latest
  commands:
    - echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
    - apk update && apk add helm
    - helm lint chart
  when:
    event:
      - pull_request

- name: template
  image: alpine:latest
  commands:
    - echo 'https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories
    - apk update && apk add helm
    - helm template git-mirror chart
  when:
    event:
      - pull_request

