---
apiVersion: v1
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;

    error_log  /dev/stderr;
    pid        /run/nginx.pid;

    daemon off;

    events {
      worker_connections {{ .Values.porter.workerConnections }};
    }

    http {
      server {
        listen  *:80;

        server_name {{ .Values.porter.url }};
        access_log /dev/stdout main;

        location ~ /git(/.*) {
          client_max_body_size 0;
          
          include fastcgi_params;
          fastcgi_param   SCRIPT_FILENAME /usr/libexec/git-core/git-http-backend;
          fastcgi_param   GIT_HTTP_EXPORT_ALL "";
          fastcgi_param   GIT_PROJECT_ROOT /var/git;
          fastcgi_param   PATH_INFO   $1;
          
          # Forward REMOTE_USER as we want to know when we are authenticated
          fastcgi_param REMOTE_USER $remote_user;
          fastcgi_pass unix:/run/fcgi.sock;
        }
      }
    }
kind: ConfigMap
metadata:
  name: git-porter
