{{- range $key, $value := .Values.sync.repositories }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
  labels:
    {{- include "git-mirror.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "git-mirror.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "git-mirror.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "git-mirror.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: git-sync
          env:
            - name: GIT_SYNC_REPO
              value: {{ $value.url }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.sync.image.repository }}:{{ $.Values.sync.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: "{{ $.Values.sync.image.pullPolicy }}"
          volumeMounts:
          - mountPath: "{{ $.Values.sync.path }}"
            name: git-data
        - name: git-porter
          image: "{{ $.Values.porter.image.repository }}:{{ $.Values.porter.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: "{{ $.Values.porter.image.pullPolicy }}"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          volumeMounts:
          - mountPath: "/var/git"
            name: git-dir
          - mountPath: "/etc/nginx/nginx.conf"
            name: git-porter
            readOnly: true
            subPath: "nginx.conf"
          - mountPath: "/etc/nginx/sites-enabled/git.conf"
            name: git-porter
            readOnly: true
            subPath: "git.conf"
      volumes:
        - name: git-dir
          emptyDir:
            medium: Memory
        - name: git-data
          emptyDir:
            medium: Memory
        - name: git-porter
          configMap:
            defaultMode: 420
            name: git-porter
            optional: false
{{- end }}
