{{- range $key, $value := .Values.sync.repositories }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}
  labels:
    {{- include "git-mirror.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.porter.service.type }}
  ports:
    - port: {{ $.Values.porter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    matchLabels:
      {{- include "git-mirror.selectorLabels" $ | nindent 6 }}
{{- end }}
