#!/bin/bash -e

regions=(us-east-1 us-east-2 us-west-1 us-west-2 eu-west-1 eu-central-1 ap-northeast-1 ap-northeast-2 ap-southeast-1 ap-southeast-2 ap-south-1 sa-east-1)
#regions=(sa-east-1)

for region in ${regions[@]}; do
  terraform "$@" -state=terraform.$region.tfstate -var "region=$region" &
done
