.catalog:
  version: 1.0.2
  minimum_rancher_version: 1.5.0
  questions:
  - variable: MIRROR_SCALE
    description: >
      Number of git mirror instances to schedule.
    label: Mirror Scale
    type: int
    default: 3
  - variable: ETCD_SCALE
    description: >
      Number of etcd instances to schedule.
    label: Etcd Scale
    type: int
    default: 3
  - variable: POLL_PERIOD
    description: >
      Poll each Git repository for changes after a configurable period of time.
    label: Polling Period
    type: string
    default: 5m
  - variable: REPO
    description: Comma-delimited list of Git repositories to mirror.
    label: Mirrored Repos
    type: string
    default: >
      https://github.com/rancher/rancher-catalog,
      https://github.com/rancher/community-catalog,
      https://github.com/rancher/infra-catalog
  - variable: DEBUG
    description: Enable debug-level logging.
    label: Debug Logging
    type: boolean
    default: false
  - variable: HOST_LOG_PATH
    description: Host path to bind mount nginx log directory to
    label: Host Log Path
    type: string
    default: /efs
  - variable: ETCD_HEARTBEAT_INTERVAL
    label: Etcd Heartbeat Interval
    description: Time (in milliseconds) of a heartbeat interval.
    required: true
    default: 500
    type: int
  - variable: ETCD_ELECTION_TIMEOUT
    label: Etcd Election Timeout
    description: Time (in milliseconds) for an election to timeout.
    required: true
    default: 5000
    type: int
  - variable: ETCD_STORAGE
    label: Etcd Storage
    description: >
      Store etcd data on the host in a local volume (persistent) or within the
      container (ephemeral).
    default: persistent
    type: enum
    options:
    - ephemeral
    - persistent
  - variable: SERVER_NAME
    label: Server Name
    description: The name of the Nginx server
    required: true
    default: git.rancher.io
    type: string
  - variable: WORKER_CONNECTIONS
    label: Nginx Worker Connections
    description: Number of connections to accept per Nginx worker process
    required: true
    default: 4096
    type: int
  - variable: LOGROTATE_SCHEDULE
    label: Log Rotation Schedule
    description: The cron-like schedule for performing logrotation on nginx containers. Default is Midnight MST.
    required: true
    default: "0 0 7 * * *"
    type: string
etcd:
  retain_ip: true
  scale: ${ETCD_SCALE}
  health_check:
    request_line: GET /health HTTP/1.0
    port: 2378
    interval: 5000
    response_timeout: 3000
    unhealthy_threshold: 2
    healthy_threshold: 2
mirror:
  scale: ${MIRROR_SCALE}
  health_check:
    request_line: GET / HTTP/1.0
    port: 80
    interval: 5000
    response_timeout: 3000
    healthy_threshold: 2
    unhealthy_threshold: 2
logrotate:
  start_on_create: false