#!/bin/bash

docker volume rm git-mirror || true

docker run \
  -d \
  -v git-mirror:/var/git \
  --restart=always \
  --name=git-mirror \
    llparse/git-mirror:0.1

docker run \
  -d \
  -v git-mirror:/var/git \
  -v git-log:/var/log/nginx \
  -p 80:80 \
  --restart=always \
  --name=git-serve \
    llparse/git-serve:0.2
