#!/bin/bash

docker volume rm git-mirror || true

docker run \
  -d \
  -v git-mirror:/var/git \
  --net=host \
  --restart=always \
  --name=git-mirror \
    llparse/git-mirror:0.1

docker run \
  -d \
  -v git-mirror:/var/git \
  -v /var/log/nginx:/var/log/nginx \
  --net=host \
  --restart=always \
  --name=git-serve \
    llparse/git-serve:0.2
