#!/bin/bash

id=$RANDOM
name=rancher-catalog
endpoint=http://master:4141

data="{\"repository\":{\"id\":$id,\"name\":\"$name\",\"full_name\":\"rancher/$name\"}}"

set -x
curl \
  -X POST \
  -d $data \
  $endpoint/postreceive
