#!/bin/bash

# Generate nginx/site configuration
confd -onetime -backend env

# Turn up services
service fcgiwrap start
service nginx start

# Send error logs to stdout
tail -f /var/log/nginx/error-${MY_POD_NAME}.log
