#!/bin/bash

docker pull llparse/git-serve
docker run \
  -d \
  -v git-mirror:/var/git \
  -v /var/log/nginx/${host}:/var/log/nginx \
  --net=host \
  --restart=always \
  --name=git-serve \
    llparse/git-serve

